name: Android CI

on:
  push:
    branches: [ main, develop ] # Trigger on pushes to main and develop branches
  pull_request:
    branches: [ main, develop ] # Trigger on pull requests targeting main and develop

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu Linux runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4 # Action to check out your repository code

    - name: Set up JDK 17
      uses: actions/setup-java@v4 # Action to set up a Java Development Kit
      with:
        distribution: 'temurin' # Recommended distribution (Adoptium Temurin)
        java-version: '17'      # Specify the Java version required for recent Android builds
        cache: 'gradle'         # Cache Gradle dependencies

    - name: Set up Android SDK (Accept Licenses)
      # This action helps in quickly setting up the SDK and accepting licenses
      # which is required for Gradle builds.
      uses: android-actions/setup-android@v3
      with:
        api-level: 34 # Specify the API level your app targets (or the highest used)
        build-tools: 34.0.0 # Specify the build tools version
        # Also accepts other options like command-line-tools, ndk, etc.

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew # Make the Gradle wrapper executable

    - name: Build Debug APK
      run: ./gradlew assembleDebug # Run the Gradle task to build the debug APK
      # Or use: ./gradlew build # This runs assembleDebug, assembleRelease, check, etc.

    # Optional: Upload the generated APKs/AABs as artifacts
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk # Path to debug APK
        
    # - name: Build Release APK
    #   run: ./gradlew assembleRelease
    # - name: Upload Release APK
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: release-apk
    #     path: app/build/outputs/apk/release/app-release-unsigned.apk # Path to your release APK (unsigned)
    
