name: Android CI

on:
  push:
    branches: [ main, develop ]  # Trigger on pushes to main and develop branches
  pull_request:
    branches: [ main, develop ]  # Trigger on pull requests targeting main and develop
  workflow_dispatch:             # Allow manual triggering via GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest       # Use the latest Ubuntu Linux runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4  # Action to check out your repository code

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Set up Android SDK (Accept Licenses)
      uses: android-actions/setup-android@v3
      with:
        api-level: 34
        build-tools: 34.0.0

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk

    # Optional: Uncomment below to build and upload release APK
    # - name: Build Release APK
    #   run: ./gradlew assembleRelease
    #
    # - name: Upload Release APK
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: release-apk
    #     path: app/build/outputs/apk/release/app-release-unsigned.apk
